INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Brasil', 0, 1);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Marrocos', 5, 4);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('França', 13, 9);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Inglaterra', 2, 3);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Espanha', 1, 4);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Holanda', 4, 4);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Portugal', 3, 3);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Bélgica', 6, 5);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Croácia', 2, 3);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Uruguai', 15, 13);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Alemanha', 0, 3);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Colômbia', 6, 5);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Suiça', 6, 5);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Estados Unidos', 0, 4);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Coreia do Sul', 10, 6);
INSERT INTO equipes (nome, gols_marcados, gols_sofridos) VALUES ('Argentina', 0, 1);

INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (1, 'Oitavas', 'Brasil', 'Marrocos', 0, 1, 'Marrocos');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (2, 'Oitavas', 'França', 'Inglaterra', 3, 2, 'França');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (3, 'Oitavas', 'Espanha', 'Holanda', 1, 4, 'Holanda');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (4, 'Oitavas', 'Portugal', 'Bélgica', 3, 3, 'Bélgica');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (5, 'Oitavas', 'Croácia', 'Uruguai', 2, 3, 'Uruguai');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (6, 'Oitavas', 'Alemanha', 'Colômbia', 0, 3, 'Colômbia');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (7, 'Oitavas', 'Suiça', 'Estados Unidos', 4, 0, 'Suiça');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (8, 'Oitavas', 'Coreia do Sul', 'Argentina', 1, 0, 'Coreia do Sul');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (9, 'Quartas', 'Marrocos', 'França', 4, 4, 'França');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (10, 'Quartas', 'Holanda', 'Bélgica', 0, 3, 'Bélgica');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (11, 'Quartas', 'Uruguai', 'Colômbia', 5, 3, 'Uruguai');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (12, 'Quartas', 'Suiça', 'Coreia do Sul', 2, 5, 'Coreia do Sul');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (13, 'Semifinal', 'França', 'Bélgica', 2, 0, 'França');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (14, 'Semifinal', 'Uruguai', 'Coreia do Sul', 4, 4, 'Uruguai');
INSERT INTO partidas (id, fase, time1, time2, gols1, gols2, vencedor) VALUES (15, 'Final', 'França', 'Uruguai', 4, 3, 'França');